# Generated by Django 6.0.7 on 2026-07-13 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_oder_address_oder_email_oder_full_name_oder_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oderitem',
            old_name='total_amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='oderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='oderitem',
            name='user',
        ),
        migrations.AddField(
            model_name='oderitem',
            name='Oder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.oder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oderitem',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
